### ISSUE TITLE
Duplicate "Biological replicate"

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/nfdi4plants_ontology#11]
The following Term: "Biological replicate" was added to the nfdi4pso ontology, even though the term already exists in the `ms` ontology. The `ms` term is even referenced in the `comment`.

> [Term] 
> id: NFDI4PSO:0000042
> name: Biological replicate
> def: "Indicates the biological replication during experiment design (e.g. 'rep1', 'rep2')"
> comment: “Similar to http://purl.obolibrary.org/obo/MS_1001809"

I propose we delete the duplicate term, except i am missing something here.

@Brilator [commit](https://github.com/nfdi4plants/nfdi4plants_ontology/commit/ad4776560c918de1ddf8c13d8d41b2671145a020#diff-24f72443f3c37f5b6eb464d6db0c526794b5bf6270eeb523017a25af56ab29f8)

**Comment by Brilator** [comment]
Def of MS_1001809: "the run was generated from another individual or sample" sounded too specific to me, esp. due to "run" and being associated to MS. 
More importantly, I guess we shouldn't delete anything from the broker ontology (just now) for persistence. But we'll have to learn how to properly develop the ontology in the future with TA1.
