### ISSUE TITLE
New terms for microscopy in our lab

### ISSUE THREAD

**Issue by christinerempfer** [nfdi4plants/nfdi4plants_ontology#48]
We have collected a list of terms with settings and devices commonly used for microscopy in our lab, that are not yet present in the DataPLANT ontology. Some are specific for our microscopes. New term names, definitions and parent terms are included in the attached Excel sheet 

[missing_terms.xlsx](https://github.com/nfdi4plants/nfdi4plants_ontology/files/10695566/missing_terms.xlsx)

Can you please add these terms to the DataPLANT ontology?

**Comment by kdumschott** [comment]
Hello, thank you for your term suggestions to help expand the dpbo.

I had a few points that I wanted to clarify about the terms you have given.

First, I would like to change the objective lens terms (see below) to be compatible with the term name given in the Zeiss micro-shop:
NEOFLUAR would become Plan-Neofluar
(ex. NEOFLUAR 63 x / 1.25 oil to Plan-Neofluar 63x/1.25 Oil) 
and 
Only the first letter of ACROPLAN would be capitalized
(ex. ACHROPLAN 5 x / 0.12 to Achroplan 5x/0.12)

Second, instead of using Objective for the parent term, I would like to use the Ncit term 'Objective Lens'.

Please let me know if these changes suit you okay and I will import them.

Best,

Kathryn

**Comment by christinerempfer** [comment]
Hello Kathryn,

thank you for looking at the terms. The proposed changes are fine.

**Comment by kdumschott** [comment]
Hello, all terms have now been added to dpbo. Please let me know if you run into any issue with them.
