### ISSUE TITLE
[NTR] helps with plant work

### ISSUE THREAD

**Issue by andreaschrader** [nfdi4plants/nfdi4plants_ontology#67]
### New term name

helps with plant work

### Definition

A person that helps at various steps of the plant growth cycle e.g. sowing seeds, separating plants at the correct age or collecting seeds. 

### Your ORCID

https://orcid.org/0000-0002-3879-7057

**Comment by kdumschott** [comment]
Hi Andrea,

Thank you for your contribution!

This NTR reads more like an object property (relation between classes/individuals) rather than a class. Unfortunately, adding this as an object property will not be compatible with Swate and OBO. Would it be okay to reword the term to be "plant work helper" instead?

-Kathryn

**Comment by andreaschrader** [comment]
Hi Kathryn,

Yes, this is a good suggestion. 
Thank you. 
Please reword is as suggested!
