### ISSUE TITLE
Integrate DataPLANT Ontology Collection in TIB Terminology Service

### ISSUE THREAD

**Issue by AngelaKranz** [nfdi4plants/nfdi4plants_ontology#76]

**Comment by AngelaKranz** [comment]
https://gitlab.com/TIBHannover/terminology/tib-terminology-service-issue-tracker/-/issues/7

**Comment by Hannah-Doerpholz** [comment]
Update: the DataPLANT collection itself is online, ontologies will be linked soon.

**Comment by Hannah-Doerpholz** [comment]
Update: So far, all ontologies inside SwateDB are also on the TS4TIB lookup service, with the exception of GO (still WIP), NCBITaxon (too large) and DPBO (WIP). Here, users can browse though ontologies and explore them, or look for specific terms they might not be aware of. We have also collected other ontologies that might be relevant to the DataPLANT community, as well as microbiologists since we have started working with researchers from this field too. The entire collection of relevant ontologies can be found here: https://terminology.tib.eu/ts/ontologies?collection=DataPLANT&and=false&page=1 . We are currently also planning to link the TS4TIB service to swate, but that is still work in progress
