### ISSUE TITLE
Add new terms for microscope models

### ISSUE THREAD

**Issue by UrsulaE** [nfdi4plants/nfdi4plants_ontology#77]
name: Zeiss Axio Observer Z1
def: "Inverted fluorescence microscope"
https://www.zeiss.com/microscopy/en/products/light-microscopes/widefield-microscopes/axio-observer-for-life-science-research.html
is_a:  CHMO:0001095 [fluorescence microscope]
Ursula Eberhardt | ORCID: 0000-0003-1221-7074

name: Zeiss Imager M1
def: "Upright fluorescence microscope"
https://microscopy.ucsf.edu/instruments/zeiss-axioimager-m1, https://profcontrol.de/Zeiss-Axio-Imager-M1m-Fluorescence-DIC-Microscope-Fluoreszenz-Mikroskop
is_a: CHMO:0001095 [fluorescence microscope]
Ursula Eberhardt | ORCID: 0000-0003-1221-7074

**Comment by kdumschott** [comment]
Currently, the parent term for all microscope models is OBI:0400169 (microscope) as this is what Swate templates (for example, see 3ASY05_Imaging) use as the heading for that particular information. I would therefore like to adhere to this instead of using the CHMO term. Please let me know if this is okay with you.

**Comment by UrsulaE** [comment]
fine with me. Thanks for your help.
