### ISSUE TITLE
[Import Ontology] SCoRO

### ISSUE THREAD

**Issue by kMutagene** [nfdi4plants/nfdi4plants_ontology#88]
### Ontology

https://sparontologies.github.io/scoro/current/scoro.html

### Please state the reason to import this ontology into the SwateDB

This ontology was requested originally on the ARCitect repo: https://github.com/nfdi4plants/ARCitect/issues/229. Importing it makes sense, especially given the case that we already recommend using it on the knowledgebase as stated in the original request.

**Comment by StellaEggels** [comment]
We unfortunately can't import it because it is not available in obo format. However the credit ontology is already included in Swate so it is probably not needed to import the whole scoro ontology as well. If there are specific terms missing we can add them manually. We should probably change the recommendation in the knowledge base.
